apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      imagePullSecrets:
        - name: image-secrets
      containers:
      - name: migration 
        image: cr.yandex/crp6fqsjle6nrluiklb6/common/backend:latest
        envFrom:
          - secretRef:
              name: secretkv
        env:
        - name: TESTING_TEMPLATE_PASS_ENCODING_SECRET
          value: 95d6ad8f6a64cd25f501488b8e773bac33746934074397b798f002e93fb6a42e
        - name: TESTING_TEMPLATE_DB_ADDRESS
          value: postgres-svc
        - name: JAEGER_BACKEND
          value: jaeger-svc-collector:4317
        - name: TESTING_TEMPLATE_DB_NAME
          value: svc-db
        - name: TESTING_TEMPLATE_DB_USER
          value: service-user
        - name: TESTING_TEMPLATE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-svc
              key: password
        command: ["alembic", "upgrade", "head"]  # Run Alembic migration
      restartPolicy: Never

