# Changes here will be overwritten by Copier
_commit: 88a337e
_src_path: https://github.com/zinchenkomig/base-users-template.git
custom_container_registry: cr.yandex
domain: mikhailzinchenko.test
email: ''
env_prefix: TESTING_TEMPLATE
image_name: cr.yandex/crp6fqsjle6nrluiklb6/common/backend
is_custom_container_registry: true
project_name: testing_template
