import os

IS_PROD = bool(int(os.getenv('TESTING_TEMPLATE_IS_PROD', '0')))

ALGORITHM = 'HS256'
ACCESS_TOKEN_EXPIRE_MINUTES = 15
REFRESH_TOKEN_EXPIRE_MINUTES = 43200

IS_SECURE_COOKIE = IS_PROD
SAME_SITE = 'lax'

APP_NAME = os.getenv('TESTING_TEMPLATE_APP_NAME', 'testing_template')

JAEGER_BACKEND = os.getenv('TESTING_TEMPLATE_JAEGER_BACKEND', 'localhost:4317')

GMAIL_API_TOKEN = os.getenv('TESTING_TEMPLATE_GMAIL_API_TOKEN', '')
FRONTEND_URL = os.getenv('TESTING_TEMPLATE_FRONTEND_URL', '')

ALLOWED_ORIGINS = [FRONTEND_URL] if IS_PROD else ['http://localhost:3000', FRONTEND_URL]

S3_ENDPOINT = os.getenv('TESTING_TEMPLATE_S3_ENDPOINT', '')
BUCKET = os.getenv('TESTING_TEMPLATE_BUCKET', '')
IS_S3_MOCK = os.getenv('TESTING_TEMPLATE_IS_S3_MOCK', '0')
