{
 "title": "FastAPI Observability 2",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "app_name", "label": "Application Name", "query": { "query": "label_values(app_name)" } }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(starlette_requests_total{app_name=\"$app_name\", path!=\"/metrics\", path!=\"/ping\"}[5m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Requests over time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(starlette_requests_total{app_name=\"$app_name\", path!=\"/metrics\", path!=\"/ping\"}[$__range]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Errors over time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(starlette_requests_total{app_name=\"$app_name\", path!=\"/metrics\", path!=\"/ping\", status_code=~\"5.*\"}[$__range]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  sort_desc(sum by (method, path) (last_over_time(starlette_request_duration_seconds_sum{app_name=\"$app_name\"}[$__range]))\n/\n  sum by (method, path) (last_over_time(starlette_request_duration_seconds_count{app_name=\"$app_name\"}[$__range])))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(method, path) (last_over_time(starlette_requests_total{app_name=\"$app_name\", status_code=~\"5.*\", path!=\"/metrics\"}[$__range])) / sum by(method, path) (last_over_time(starlette_requests_total{app_name=\"$app_name\", path!=\"/metrics\"}[$__range]))",
     "legendFormat": "{{method}}{{path}}"
    }
   ]
  },
  {
   "title": "Backend Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "appName: \"base-users-backend\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}