
mode: standalone
statefulset:
  replicaCount: 1

ingress:
  enabled: true
  hostname: console.s3.mikhailzinchenko.test

apiIngress:
  enabled: true
  hostname: s3.mikhailzinchenko.test
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
  tls:
    - secretName: zinchenkomig-minio-tls
      hosts:
        - s3.mikhailzinchenko.test

provisioning:
  enabled: true
  buckets:
    - name: svc-buck
      withLock: true
