"""superuser_flag

Revision ID: 186679019f3e
Revises: 81831d42b299
Create Date: 2023-04-21 01:20:28.189071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186679019f3e'
down_revision = '81831d42b299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###
