"""tg_data

Revision ID: d55f4601cf7c
Revises: abac42ef5dff
Create Date: 2024-01-28 02:45:28.142224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd55f4601cf7c'
down_revision = 'abac42ef5dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('origin', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('photo_url', sa.Text(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('users', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('users', 'photo_url')
    op.drop_column('users', 'origin')
    # ### end Alembic commands ###
