"""tg_id

Revision ID: 40494670ef24
Revises: d55f4601cf7c
Create Date: 2024-06-01 03:12:01.240470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40494670ef24'
down_revision = 'd55f4601cf7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_id', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('roles', sa.ARRAY(sa.Text()), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'origin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('origin', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'roles')
    op.drop_column('users', 'tg_id')
    # ### end Alembic commands ###
