"""user_guid

Revision ID: 1b62183ad262
Revises: 7078190ecb08
Create Date: 2024-06-20 22:31:04.970667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b62183ad262'
down_revision = '7078190ecb08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id', new_column_name='guid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'guid', new_column_name='id')
    # ### end Alembic commands ###
