"""users_new_scheme

Revision ID: bae2e0cfdf38
Revises: 62ce53894520
Create Date: 2024-09-15 10:23:17.507798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae2e0cfdf38'
down_revision = '62ce53894520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_username', sa.Text(), nullable=True))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('users', 'tg_username')
    # ### end Alembic commands ###
