server:
  dataStorage:
    enabled: true
  standalone:
    enabled: true
  logLevel: debug
  # service:
  #   enabled: true
  #   type: ClusterIP
  #   # Port on which Vault server is listening
  #   port: 8200
  #   # Target port to which the service should be mapped to
  #   targetPort: 8200
  ingress:
    enabled: true
    hosts:
     - host: vault.mikhailzinchenko.test
       paths:
        - /
ui:
  enabled: true
  serviceType: "ClusterIP"
  externalPort: 8200

injector:
  enabled: "false"
